version: '3.8'

services:
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: course_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - course_network

  postgres:
    image: postgres:15
    container_name: course_postgres
    environment:
      POSTGRES_DB: course_platform
      POSTGRES_USER: course_user
      POSTGRES_PASSWORD: course_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - course_network

volumes:
  postgres_data:
  pgadmin_data:

networks:
  course_network:
    driver: bridge